/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthClientMetadataDotjsonRouteImport } from './routes/oauth/client-metadata[.]json'
import { Route as ConnectN8nRouteImport } from './routes/connect/n8n'
import { Route as OauthN8nResultRouteImport } from './routes/oauth/n8n/result'
import { Route as OauthN8nCallbackRouteImport } from './routes/oauth/n8n/callback'
import { Route as ApiN8nToolsRouteImport } from './routes/api/n8n/tools'
import { Route as ApiN8nCallRouteImport } from './routes/api/n8n/call'

const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthClientMetadataDotjsonRoute =
  OauthClientMetadataDotjsonRouteImport.update({
    id: '/oauth/client-metadata.json',
    path: '/oauth/client-metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectN8nRoute = ConnectN8nRouteImport.update({
  id: '/connect/n8n',
  path: '/connect/n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthN8nResultRoute = OauthN8nResultRouteImport.update({
  id: '/oauth/n8n/result',
  path: '/oauth/n8n/result',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthN8nCallbackRoute = OauthN8nCallbackRouteImport.update({
  id: '/oauth/n8n/callback',
  path: '/oauth/n8n/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nToolsRoute = ApiN8nToolsRouteImport.update({
  id: '/api/n8n/tools',
  path: '/api/n8n/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiN8nCallRoute = ApiN8nCallRouteImport.update({
  id: '/api/n8n/call',
  path: '/api/n8n/call',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/connect/n8n': typeof ConnectN8nRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/api/n8n/call': typeof ApiN8nCallRoute
  '/api/n8n/tools': typeof ApiN8nToolsRoute
  '/oauth/n8n/callback': typeof OauthN8nCallbackRoute
  '/oauth/n8n/result': typeof OauthN8nResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/connect/n8n': typeof ConnectN8nRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/api/n8n/call': typeof ApiN8nCallRoute
  '/api/n8n/tools': typeof ApiN8nToolsRoute
  '/oauth/n8n/callback': typeof OauthN8nCallbackRoute
  '/oauth/n8n/result': typeof OauthN8nResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/connect/n8n': typeof ConnectN8nRoute
  '/oauth/client-metadata.json': typeof OauthClientMetadataDotjsonRoute
  '/api/n8n/call': typeof ApiN8nCallRoute
  '/api/n8n/tools': typeof ApiN8nToolsRoute
  '/oauth/n8n/callback': typeof OauthN8nCallbackRoute
  '/oauth/n8n/result': typeof OauthN8nResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/openapi.json'
    | '/connect/n8n'
    | '/oauth/client-metadata.json'
    | '/api/n8n/call'
    | '/api/n8n/tools'
    | '/oauth/n8n/callback'
    | '/oauth/n8n/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/openapi.json'
    | '/connect/n8n'
    | '/oauth/client-metadata.json'
    | '/api/n8n/call'
    | '/api/n8n/tools'
    | '/oauth/n8n/callback'
    | '/oauth/n8n/result'
  id:
    | '__root__'
    | '/'
    | '/openapi.json'
    | '/connect/n8n'
    | '/oauth/client-metadata.json'
    | '/api/n8n/call'
    | '/api/n8n/tools'
    | '/oauth/n8n/callback'
    | '/oauth/n8n/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  ConnectN8nRoute: typeof ConnectN8nRoute
  OauthClientMetadataDotjsonRoute: typeof OauthClientMetadataDotjsonRoute
  ApiN8nCallRoute: typeof ApiN8nCallRoute
  ApiN8nToolsRoute: typeof ApiN8nToolsRoute
  OauthN8nCallbackRoute: typeof OauthN8nCallbackRoute
  OauthN8nResultRoute: typeof OauthN8nResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/client-metadata.json': {
      id: '/oauth/client-metadata.json'
      path: '/oauth/client-metadata.json'
      fullPath: '/oauth/client-metadata.json'
      preLoaderRoute: typeof OauthClientMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/n8n': {
      id: '/connect/n8n'
      path: '/connect/n8n'
      fullPath: '/connect/n8n'
      preLoaderRoute: typeof ConnectN8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/n8n/result': {
      id: '/oauth/n8n/result'
      path: '/oauth/n8n/result'
      fullPath: '/oauth/n8n/result'
      preLoaderRoute: typeof OauthN8nResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/n8n/callback': {
      id: '/oauth/n8n/callback'
      path: '/oauth/n8n/callback'
      fullPath: '/oauth/n8n/callback'
      preLoaderRoute: typeof OauthN8nCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n/tools': {
      id: '/api/n8n/tools'
      path: '/api/n8n/tools'
      fullPath: '/api/n8n/tools'
      preLoaderRoute: typeof ApiN8nToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/n8n/call': {
      id: '/api/n8n/call'
      path: '/api/n8n/call'
      fullPath: '/api/n8n/call'
      preLoaderRoute: typeof ApiN8nCallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  ConnectN8nRoute: ConnectN8nRoute,
  OauthClientMetadataDotjsonRoute: OauthClientMetadataDotjsonRoute,
  ApiN8nCallRoute: ApiN8nCallRoute,
  ApiN8nToolsRoute: ApiN8nToolsRoute,
  OauthN8nCallbackRoute: OauthN8nCallbackRoute,
  OauthN8nResultRoute: OauthN8nResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
